# All project-specific additions and overrides should be specified in this 
# file.

inherit_from:
  - https://raw.githubusercontent.com/riboseinc/oss-guides/master/ci/rubocop.yml

AllCops:
  DisplayCopNames: false
  StyleGuideCopsOnly: false
  TargetRubyVersion: 2.4

Rails:
  Enabled: true
