# All project-specific additions and overrides should be specified in this
# file.

inherit_from:
  - https://raw.githubusercontent.com/riboseinc/oss-guides/master/ci/rubocop.yml

require: rubocop-rails

AllCops:
  DisplayCopNames: false
  StyleGuideCopsOnly: false
  TargetRubyVersion: 2.4

Rails:
  Enabled: true

# It's not a typical Rails application.  There is no value in introducing
# the ApplicationRecord class.
Rails/ApplicationRecord:
  Enabled: false
